<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="site" nsURI="tag:scheidt-bachmann-st.de,2018-05-18:planpro/site"
    nsPrefix="site">
  <eClassifiers xsi:type="ecore:EClass" name="Site">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allBuildings" upperBound="-1"
        eType="#//Building" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allFloors" upperBound="-1"
        eType="#//Floor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPassages" upperBound="-1"
        eType="#//Passage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//Identified">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" lowerBound="1" eType="#//BuildingNames"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildingsInTheSameStreet"
        upperBound="-1" eType="#//Building"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//Identified">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" lowerBound="1" eType="#//RoomNames"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="windows" upperBound="-1"
        eType="#//Window" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identified">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Floor" eSuperTypes="#//Identified">
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" lowerBound="1" eType="#//FloorNames"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildingID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildingNames">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entrance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sitePlan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloorNames">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elevator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floorPlanTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomNames">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSign" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floorPlan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Passage" eSuperTypes="#//Identified">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomID_A" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomID_B" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Window">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//WindowType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WindowType">
    <eLiterals name="SIMPLE"/>
    <eLiterals name="TOP_HUNG" value="1"/>
    <eLiterals name="BOTTOM_HUNG" value="2"/>
    <eLiterals name="BARRED" value="3"/>
    <eLiterals name="MOSAIC" value="4"/>
  </eClassifiers>
</ecore:EPackage>
