<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tablemodel" nsURI="tag:scheidt-bachmann-st.de,2016-10-11:planpro/tm"
    nsPrefix="tm">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The table model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columndescriptors" lowerBound="1"
        upperBound="-1" eType="#//ColumnDescriptor" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The description of the column headers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablecontent" lowerBound="1"
        eType="#//TableContent" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The dynamic content of the table."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColumnWidthMode">
    <eLiterals name="WIDTH_CM"/>
    <eLiterals name="WIDTH_PERCENT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Header column description."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The width of the column in cm."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="widthMode" eType="#//ColumnWidthMode"
        defaultValueLiteral="WIDTH_CM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ColumnDescriptor" eOpposite="#//ColumnDescriptor/parent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Header children."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The label of the column."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="greyed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Flag for greyed out columns."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether this descriptor describes a unit."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ColumnDescriptor"
        eOpposite="#//ColumnDescriptor/children">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parent of this header."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The height of the row in cm."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeCommonValues" eType="#//RowMergeMode"
        defaultValueLiteral="DEFAULT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The position of this column"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableContent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The dynamic content of the table."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowgroups" upperBound="-1"
        eType="#//RowGroup" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of row groups."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Leading object of a group of table rows."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//TableRow"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of table rows belonging to the leading object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadingObject" eType="ecore:EClass ../../org.eclipse.set.model.planpro/model/Basisobjekte.ecore#//Ur_Objekt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The guid of the leading object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leadingObjectIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Representation of one row in the table."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//TableCell" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of cells of the row."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footnotes" eType="#//FootnoteContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCell">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Representation of a cell in the table."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//CellContent"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The content of the cell"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columndescriptor" lowerBound="1"
        eType="#//ColumnDescriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The column header information."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellannotation" upperBound="-1"
        eType="#//CellAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellContent" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Content of a table cell."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringCellContent" eSuperTypes="#//CellContent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Standard cell with text."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareStateCellContent" eSuperTypes="#//CellContent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Result of a compare operation between two cells."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldValue" eType="#//CellContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" eType="#//CellContent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiColorCellContent" eSuperTypes="#//CellContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//MultiColorContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiColorContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiColorValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableMultiColor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RowMergeMode">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="ENABLED" value="1" literal="ENABLED"/>
    <eLiterals name="DISABLED" value="2" literal="DISABLED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FootnoteContainer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompareFootnoteContainer" eSuperTypes="#//FootnoteContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldFootnotes" eType="#//SimpleFootnoteContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newFootnotes" eType="#//SimpleFootnoteContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unchangedFootnotes" eType="#//SimpleFootnoteContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleFootnoteContainer" eSuperTypes="#//FootnoteContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="footnotes" upperBound="-1"
        eType="#//Footnote"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareTableCellContent" eSuperTypes="#//CellContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainPlanCellContent" eType="#//CellContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparePlanCellContent"
        eType="#//CellContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareTableFootnoteContainer" eSuperTypes="#//FootnoteContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainPlanFootnoteContainer"
        eType="#//FootnoteContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparePlanFootnoteContainer"
        eType="#//FootnoteContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanCompareRow" eSuperTypes="#//TableRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowType" lowerBound="1"
        eType="#//PlanCompareRowType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlanCompareRowType">
    <eLiterals name="NEW_ROW"/>
    <eLiterals name="REMOVED_ROW" value="1"/>
    <eLiterals name="CHANGED_GUID_ROW" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Footnote">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bearbeitungsvermerk" eType="ecore:EClass ../../org.eclipse.set.model.planpro/model/Basisobjekte.ecore#//Bearbeitungsvermerk"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
