name: Quality

on:
  pull_request:
    paths:
      - '**/java/**'
      - 'web/siteplan/**'
      - 'web/textviewer/**'
  push:
    tags:
      - 'v**'
    branches:
      - 'release/**'
      - 'main'

run-name: Qualtity - ${{github.event_name == 'push' && github.event.head_commit.message || github.event_name == 'pull_request' && github.event.pull_request.title || 'Unknow name'}}
jobs:
  java-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: eclipse-set/build/.github/actions/setup-java@main

      - name: Cache Eclipse
        uses: actions/cache/restore@v5
        with:
          path: ./tmp/eclipse-2025-12.tar.gz
          key: ${{ runner.os }}-eclipse-2025-12

      - name: Get eclipse
        if: ${{ hashFiles('./tmp/eclipse-2025-12.tar.gz') == '' }}
        run: mkdir ./tmp && wget -O ./tmp/eclipse-2025-12.tar.gz https://archive.eclipse.org/technology/epp/downloads/release/2025-12/RC1/eclipse-java-2025-12-RC1-linux-gtk-x86_64.tar.gz

      - name: Save to Cache
        uses: actions/cache/save@v5
        with:
          path: ./tmp/eclipse-2025-12.tar.gz
          key: ${{ runner.os }}-eclipse-2025-12
          
      - name: Unzip eclipse
        run: tar -xf ./tmp/eclipse-2025-12.tar.gz -C ./tmp

      - name: Test
        run: ls -la $JAVA_HOME/bin

      - name: Run eclipse formatter
        run: ./tmp/eclipse/eclipse -noSplash -vm "$JAVA_HOME/bin/java" -data ./tmp/workspace -application org.eclipse.jdt.core.JavaCodeFormatter -config ./releng/eclipse/java-formatter.epf .

      - name: Cleanup eclipse
        run: rm -R ./tmp
      
      - name: Print diffs
        run: git --no-pager diff --exit-code

  lint-siteplan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: web/siteplan

      - name: Eslint
        run: npm run lint
        working-directory: web/siteplan

  lint-textviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: cd web/textviewer && npm install

      - name: Eslint
        run: cd web/textviewer && npm run lint

