name: Update table reference

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull request number'
        required: true
        type: number
  pull_request:
    branches:
      - 'swtbot/test'
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  doCommand:
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/update-table-reference'))
    container: ghcr.io/truongquangsb/update-table-reference:latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
      actions: read
    steps:
      - name: is Comment
        if: github.event_name == 'issue_comment'
        shell: bash
        run: python -m updatereference -prNumber=${{github.event.issue.number}}

      - name: is workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: python -m updatereference -prNumber=${{inputs.prNumber}}
        
      - name: Add comment reaction
        uses: actions/github-script@v7
        with:
          script: |
            const payload = await github.rest.repos.getCollaboratorPermissionLevel({
              ...context.repo, username: context.actor
            });
            const userPermission = payload?.data?.permission;
            let reaction = 'rocket'
            if (!(userPermission == 'write' || userPermission == 'admin')) { // not a committer
              // Not a committer -> abort workflow
              core.setFailed("Only committers are permitted to request license vetting and " + context.actor + " isn't one.")
              reaction = '-1'
            }
            // react on comment to give early feedback that the request was understood
            await github.rest.reactions.createForIssueComment({
              ...context.repo, comment_id: context.payload?.comment?.id, content: reaction
            });


    
