name: Update DEPENDENCIES

on: 
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - DEPENDENCIES

jobs:
  dependencies:
    uses: eclipse-set/build/.github/workflows/update-dependencies.yml@main
    secrets: inherit
