name: Update table reference

on:
  push:
  pull_request:
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  doCommand:
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/update-table-reference'))
    container: ghcr.io/truongquangsb/update-table-reference:latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: swtbot/test
      
      - name: Apply changes
        shell: bash
        run: |
          ls
          python -u -m updatereference --prNumber=861
          
      - name: Push
        shell: bash
        run: |
          git config user.name 'eclipse-set-bot'
          git config user.email 'set-bot@eclipse.org'
          git status
          git branch -D swtbot/test || true
          git checkout -b swtbot/test
          git status
          git add -A
          git commit --allow-empty -m "Update table reference" 
          git status
          git push -f -u origin swtbot/test
          git status
    
